### ISSUE TITLE
Missing metadata for engine-plugins folder

### ISSUE THREAD

**Issue by scpeters** [ignition-release/ign-rendering4-release#2]
The 4.1.0 debbuild jobs are unstable, with several files installed but not referenced in `.install` files. I believe this is connected to https://github.com/ignitionrobotics/ign-rendering/pull/141.

~~~
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering4-ogre2.so.4 exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering4-ogre2.so exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering-ogre.so exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering4-ogre.so.4.1.0 exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering-ogre2.so exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering4-ogre.so exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering4-ogre2.so.4.1.0 exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/ign-rendering-4/engine-plugins/libignition-rendering4-ogre.so.4 exists in debian/tmp but is not installed to anywhere
~~~

* ubuntu/focal::amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=156)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/156/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/156/
* ubuntu/focal::arm64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=158)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/158/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/158/
* ubuntu/bionic::amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=159)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/159/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/159/
* ubuntu/bionic::i386 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=160)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/160/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/160/
* ubuntu/bionic::arm64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=163)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/163/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/163/
* debian/buster::amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=162)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/162/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/162/

**Comment by iche033** [comment]
I think we just need to port ignition-release/ign-rendering3-release#1 to this repo?

**Comment by iche033** [comment]
pull request #3

**Comment by scpeters** [comment]
4.1.0-2 ubuntu/focal::amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=167)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/167/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/167/

**Comment by scpeters** [comment]
4.1.0-2 ubuntu/bionic::amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=168)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/168/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/168/

4.1.0-2 debian/buster::amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=169)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/169/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/169/

**Comment by scpeters** [comment]
4.1.0-2 ubuntu/bionic::i386 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=170)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/170/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/170/

4.1.0-2 ubuntu/focal::arm64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=171)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/171/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/171/

4.1.0-2 ubuntu/bionic::arm64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering4-debbuilder&build=172)](https://build.osrfoundation.org/job/ign-rendering4-debbuilder/172/) https://build.osrfoundation.org/job/ign-rendering4-debbuilder/172/
